; Please do not edit this file! If this file is modified, MEGA-CC will abort any analyses initiated with this file.
; Instead of modifying this file, simply create a new MEGA Analysis Options file by using the MEGA Prototyper.
[ MEGAinfo ]
ver=0
CRC=FE5696E4
[ DataSettings ]
datatype=snNucleotide
containsCodingNuc=True
missingBaseSymbol=?
identicalBaseSymbol=.
gapSymbol=-
[ ProcessTypes ]
ppDistEst=true
ppPairTaxa=true
[ AnalysisSettings ]
Analysis=Distance Estimation
Scope=Pairs of taxa
Estimate Variance=====================
Variance Estimation Method=None
No. of Bootstrap Replications=Not Applicable
Substitution Model=====================
Substitutions Type=Nucleotide
Genetic Code Table=Not Applicable
Model/Method=Maximum Composite Likelihood
Fixed Transition/Transversion Ratio=Not Applicable
Substitutions to Include=R = s/v
Rates and Patterns=====================
Rates among Sites=Uniform rates
Gamma Parameter=Not Applicable
Pattern among Lineages=Same (Homogeneous)
Data Subset to Use=====================
Gaps/Missing Data Treatment=Complete deletion
Site Coverage Cutoff (%)=Not Applicable
Select Codon Positions=1st, 2nd, 3rd, Non-Coding
